import React from 'react'

export default function CountryCode({ setCountryCode, search, setSearch, setSearchable, searchable }) {
    return (
        <div className={`absolute z-50 top-[2.6rem] left-0 bg-slate-300 rounded-md ${!searchable > 0 && "hidden"} max-h-[375px] overflow-auto shadow-[0_0_5px_white] text-sm`} >
            <input name='search' type="text" value={search} onChange={e => setSearch(e.target.value)} className='sticky top-0 left-0 w-full outline-none invalid:text-pink-600 font-semibold bg-gray-200 focus:bg-blue-200/90 py-[6px] px-5 rounded-md shadow-[0_0_2px_blue_inset]' placeholder='search country code' />
            <div className="flex flex-col" onClick={e => setSearchable(false) | setSearch('')}>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+93 (afghanistan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+93 (Afghanistan)")}>+93 (Afghanistan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+355 (albania)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+355 (Albania)")}>+355 (Albania)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+213 (algeria)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+213 (Algeria)")}>+213 (Algeria)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1684 (american samoa)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1684 (American Samoa)")}>+1684 (American Samoa)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+376 (andorra)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+376 (Andorra)")}>+376 (Andorra)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+244 (angola)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+244 (Angola)")}>+244 (Angola)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1264 (anguilla)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1264 (Anguilla)")}>+1264 (Anguilla)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+672 (antarctica)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+672 (Antarctica)")}>+672 (Antarctica)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1268 (antigua and barbuda)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1268 (Antigua and Barbuda)")}>+1268 (Antigua and Barbuda)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+54 (argentina)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+54 (Argentina)")}>+54 (Argentina)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+374 (armenia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+374 (Armenia)")}>+374 (Armenia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+297 (aruba)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+297 (Aruba)")}>+297 (Aruba)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+61 (australia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+61 (Australia)")}>+61 (Australia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+43 (austria)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+43 (Austria)")}>+43 (Austria)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+994 (azerbaijan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+994 (Azerbaijan)")}>+994 (Azerbaijan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1242 (bahamas)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1242 (Bahamas)")}>+1242 (Bahamas)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+973 (bahrain)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+973 (Bahrain)")}>+973 (Bahrain)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+880 (bangladesh)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+880 (Bangladesh)")}>+880 (Bangladesh)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1246 (barbados)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1246 (Barbados)")}>+1246 (Barbados)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+375 (belarus)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+375 (Belarus)")}>+375 (Belarus)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+32 (belgium)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+32 (Belgium)")}>+32 (Belgium)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+501 (belize)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+501 (Belize)")}>+501 (Belize)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+229 (benin)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+229 (Benin)")}>+229 (Benin)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1441 (bermuda)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1441 (Bermuda)")}>+1441 (Bermuda)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+975 (bhutan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+975 (Bhutan)")}>+975 (Bhutan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+591 (bolivia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+591 (Bolivia)")}>+591 (Bolivia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+387 (bosnia and herzegovina)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+387 (Bosnia and Herzegovina)")}>+387 (Bosnia and Herzegovina)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+267 (botswana)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+267 (Botswana)")}>+267 (Botswana)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+55 (brazil)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+55 (Brazil)")}>+55 (Brazil)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+246 (british indian ocean territory)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+246 (British Indian Ocean Territory)")}>+246 (British Indian Ocean Territory)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+673 (brunei darussalam)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+673 (Brunei Darussalam)")}>+673 (Brunei Darussalam)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+359 (bulgaria)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+359 (Bulgaria)")}>+359 (Bulgaria)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+226 (burkina faso)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+226 (Burkina Faso)")}>+226 (Burkina Faso)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+257 (burundi)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+257 (Burundi)")}>+257 (Burundi)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+855 (cambodia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+855 (Cambodia)")}>+855 (Cambodia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+237 (cameroon)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+237 (Cameroon)")}>+237 (Cameroon)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 (canada)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 (Canada)")}>+1 (Canada)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+238 (cape verde)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+238 (Cape Verde)")}>+238 (Cape Verde)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1345 (cayman islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1345 (Cayman Islands)")}>+1345 (Cayman Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+236 (central african republic)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+236 (Central African Republic)")}>+236 (Central African Republic)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+235 (chad)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+235 (Chad)")}>+235 (Chad)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+56 (chile)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+56 (Chile)")}>+56 (Chile)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+86 (china)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+86 (China)")}>+86 (China)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+61 (christmas island)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+61 (Christmas Island)")}>+61 (Christmas Island)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+61 (cocos (keeling) islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+61 (Cocos (Keeling) Islands)")}>+61 (Cocos (Keeling) Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+57 (colombia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+57 (Colombia)")}>+57 (Colombia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+269 (comoros)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+269 (Comoros)")}>+269 (Comoros)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+242 (congo)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+242 (Congo)")}>+242 (Congo)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+243 (congo, the democratic republic of the)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+243 (Congo, The Democratic Republic of The)")}>+243 (Congo, The Democratic Republic of The)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+682 (cook islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+682 (Cook Islands)")}>+682 (Cook Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+506 (costa rica)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+506 (Costa Rica)")}>+506 (Costa Rica)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+225 (cote d'ivoire)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+225 (Cote D'Ivoire)")}>+225 (Cote D&apos;Ivoire)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+385 (croatia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+385 (Croatia)")}>+385 (Croatia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+53 (cuba)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+53 (Cuba)")}>+53 (Cuba)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+357 (cyprus)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+357 (Cyprus)")}>+357 (Cyprus)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+420 (czech republic)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+420 (Czech Republic)")}>+420 (Czech Republic)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+45 (denmark)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+45 (Denmark)")}>+45 (Denmark)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+253 (djibouti)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+253 (Djibouti)")}>+253 (Djibouti)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1767 (dominica)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1767 (Dominica)")}>+1767 (Dominica)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1849 (dominican republic)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1849 (Dominican Republic)")}>+1849 (Dominican Republic)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+593 (ecuador)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+593 (Ecuador)")}>+593 (Ecuador)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+20 (egypt)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+20 (Egypt)")}>+20 (Egypt)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+503 (el salvador)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+503 (El Salvador)")}>+503 (El Salvador)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+240 (equatorial guinea)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+240 (Equatorial Guinea)")}>+240 (Equatorial Guinea)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+291 (eritrea)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+291 (Eritrea)")}>+291 (Eritrea)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+372 (estonia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+372 (Estonia)")}>+372 (Estonia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+251 (ethiopia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+251 (Ethiopia)")}>+251 (Ethiopia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+500 (falkland islands (malvinas))".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+500 (Falkland Islands (Malvinas))")}>+500 (Falkland Islands (Malvinas))</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+298 (faroe islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+298 (Faroe Islands)")}>+298 (Faroe Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+679 (fiji)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+679 (Fiji)")}>+679 (Fiji)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+358 (finland)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+358 (Finland)")}>+358 (Finland)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+33 (france)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+33 (France)")}>+33 (France)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+594 (french guiana)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+594 (French Guiana)")}>+594 (French Guiana)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+689 (french polynesia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+689 (French Polynesia)")}>+689 (French Polynesia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+241 (gabon)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+241 (Gabon)")}>+241 (Gabon)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+220 (gambia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+220 (Gambia)")}>+220 (Gambia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+995 (georgia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+995 (Georgia)")}>+995 (Georgia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+49 (germany)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+49 (Germany)")}>+49 (Germany)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+233 (ghana)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+233 (Ghana)")}>+233 (Ghana)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+350 (gibraltar)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+350 (Gibraltar)")}>+350 (Gibraltar)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+30 (greece)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+30 (Greece)")}>+30 (Greece)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+299 (greenland)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+299 (Greenland)")}>+299 (Greenland)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1473 (grenada)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1473 (Grenada)")}>+1473 (Grenada)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+590 (guadeloupe)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+590 (Guadeloupe)")}>+590 (Guadeloupe)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1671 (guam)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1671 (Guam)")}>+1671 (Guam)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+502 (guatemala)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+502 (Guatemala)")}>+502 (Guatemala)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+224 (guinea)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+224 (Guinea)")}>+224 (Guinea)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+245 (guinea-bissau)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+245 (Guinea-Bissau)")}>+245 (Guinea-Bissau)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+592 (guyana)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+592 (Guyana)")}>+592 (Guyana)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+509 (haiti)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+509 (Haiti)")}>+509 (Haiti)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+504 (honduras)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+504 (Honduras)")}>+504 (Honduras)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+852 (hong kong)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+852 (Hong Kong)")}>+852 (Hong Kong)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+36 (hungary)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+36 (Hungary)")}>+36 (Hungary)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+354 (iceland)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+354 (Iceland)")}>+354 (Iceland)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+91 (india)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+91 (India)")}>+91 (India)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+62 (indonesia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+62 (Indonesia)")}>+62 (Indonesia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+98 (iran, islamic republic of)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+98 (Iran, Islamic Republic of)")}>+98 (Iran, Islamic Republic of)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+964 (iraq)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+964 (Iraq)")}>+964 (Iraq)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+353 (ireland)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+353 (Ireland)")}>+353 (Ireland)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+972 (israel)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+972 (Israel)")}>+972 (Israel)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+39 (italy)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+39 (Italy)")}>+39 (Italy)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1876 (jamaica)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1876 (Jamaica)")}>+1876 (Jamaica)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+81 (japan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+81 (Japan)")}>+81 (Japan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+962 (jordan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+962 (Jordan)")}>+962 (Jordan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+7 (kazakhstan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+7 (Kazakhstan)")}>+7 (Kazakhstan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+254 (kenya)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+254 (Kenya)")}>+254 (Kenya)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+686 (kiribati)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+686 (Kiribati)")}>+686 (Kiribati)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+850 (korea, democratic people's republic of)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+850 (Korea, Democratic People's Republic of)")}>+850 (Korea, Democratic People&apos;s Republic of)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+82 (korea, republic of)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+82 (Korea, Republic of)")}>+82 (Korea, Republic of)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+965 (kuwait)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+965 (Kuwait)")}>+965 (Kuwait)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+996 (kyrgyzstan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+996 (Kyrgyzstan)")}>+996 (Kyrgyzstan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+856 (lao people's democratic republic)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+856 (Lao People's Democratic Republic)")}>+856 (Lao People&apos;s Democratic Republic)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+371 (latvia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+371 (Latvia)")}>+371 (Latvia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+961 (lebanon)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+961 (Lebanon)")}>+961 (Lebanon)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+266 (lesotho)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+266 (Lesotho)")}>+266 (Lesotho)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+231 (liberia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+231 (Liberia)")}>+231 (Liberia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+218 (libya)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+218 (Libya)")}>+218 (Libya)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+423 (liechtenstein)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+423 (Liechtenstein)")}>+423 (Liechtenstein)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+370 (lithuania)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+370 (Lithuania)")}>+370 (Lithuania)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+352 (luxembourg)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+352 (Luxembourg)")}>+352 (Luxembourg)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+853 (macao)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+853 (Macao)")}>+853 (Macao)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+389 (macedonia, the former yugoslav republic of)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+389 (Macedonia, the Former Yugoslav Republic of)")}>+389 (Macedonia, the Former Yugoslav Republic of)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+261 (madagascar)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+261 (Madagascar)")}>+261 (Madagascar)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+265 (malawi)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+265 (Malawi)")}>+265 (Malawi)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+60 (malaysia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+60 (Malaysia)")}>+60 (Malaysia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+960 (maldives)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+960 (Maldives)")}>+960 (Maldives)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+223 (mali)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+223 (Mali)")}>+223 (Mali)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+356 (malta)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+356 (Malta)")}>+356 (Malta)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+692 (marshall islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+692 (Marshall Islands)")}>+692 (Marshall Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+596 (martinique)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+596 (Martinique)")}>+596 (Martinique)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+222 (mauritania)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+222 (Mauritania)")}>+222 (Mauritania)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+230 (mauritius)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+230 (Mauritius)")}>+230 (Mauritius)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+262 (mayotte)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+262 (Mayotte)")}>+262 (Mayotte)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+52 (mexico)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+52 (Mexico)")}>+52 (Mexico)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+691 (micronesia, federated states of)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+691 (Micronesia, Federated States of)")}>+691 (Micronesia, Federated States of)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+373 (moldova, republic of)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+373 (Moldova, Republic of)")}>+373 (Moldova, Republic of)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+377 (monaco)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+377 (Monaco)")}>+377 (Monaco)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+976 (mongolia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+976 (Mongolia)")}>+976 (Mongolia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+382 (montenegro)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+382 (Montenegro)")}>+382 (Montenegro)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1664 (montserrat)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1664 (Montserrat)")}>+1664 (Montserrat)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+212 (morocco)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+212 (Morocco)")}>+212 (Morocco)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+258 (mozambique)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+258 (Mozambique)")}>+258 (Mozambique)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+95 (myanmar)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+95 (Myanmar)")}>+95 (Myanmar)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+264 (namibia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+264 (Namibia)")}>+264 (Namibia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+674 (nauru)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+674 (Nauru)")}>+674 (Nauru)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+977 (nepal)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+977 (Nepal)")}>+977 (Nepal)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+31 (netherlands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+31 (Netherlands)")}>+31 (Netherlands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+687 (new caledonia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+687 (New Caledonia)")}>+687 (New Caledonia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+64 (new zealand)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+64 (New Zealand)")}>+64 (New Zealand)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+505 (nicaragua)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+505 (Nicaragua)")}>+505 (Nicaragua)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+227 (niger)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+227 (Niger)")}>+227 (Niger)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+234 (nigeria)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+234 (Nigeria)")}>+234 (Nigeria)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+683 (niue)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+683 (Niue)")}>+683 (Niue)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+672 (norfolk island)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+672 (Norfolk Island)")}>+672 (Norfolk Island)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1670 (northern mariana islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1670 (Northern Mariana Islands)")}>+1670 (Northern Mariana Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+47 (norway)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+47 (Norway)")}>+47 (Norway)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+968 (oman)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+968 (Oman)")}>+968 (Oman)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+92 (pakistan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+92 (Pakistan)")}>+92 (Pakistan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+680 (palau)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+680 (Palau)")}>+680 (Palau)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+970 (palestinian territory, occupied)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+970 (Palestinian Territory, Occupied)")}>+970 (Palestinian Territory, Occupied)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+507 (panama)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+507 (Panama)")}>+507 (Panama)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+675 (papua new guinea)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+675 (Papua New Guinea)")}>+675 (Papua New Guinea)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+595 (paraguay)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+595 (Paraguay)")}>+595 (Paraguay)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+51 (peru)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+51 (Peru)")}>+51 (Peru)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+63 (philippines)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+63 (Philippines)")}>+63 (Philippines)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+64 (pitcairn)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+64 (Pitcairn)")}>+64 (Pitcairn)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+48 (poland)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+48 (Poland)")}>+48 (Poland)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+351 (portugal)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+351 (Portugal)")}>+351 (Portugal)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1787 (puerto rico)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1787 (Puerto Rico)")}>+1787 (Puerto Rico)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+974 (qatar)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+974 (Qatar)")}>+974 (Qatar)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+262 (réunion)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+262 (Réunion)")}>+262 (Réunion)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+40 (romania)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+40 (Romania)")}>+40 (Romania)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+7 (russian federation)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+7 (Russian Federation)")}>+7 (Russian Federation)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+250 (rwanda)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+250 (Rwanda)")}>+250 (Rwanda)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+290 (saint helena, ascension and tristan da cunha)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+290 (Saint Helena, Ascension and Tristan da Cunha)")}>+290 (Saint Helena, Ascension and Tristan da Cunha)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1869 (saint kitts and nevis)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1869 (Saint Kitts and Nevis)")}>+1869 (Saint Kitts and Nevis)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1758 (saint lucia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1758 (Saint Lucia)")}>+1758 (Saint Lucia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+508 (saint pierre and miquelon)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+508 (Saint Pierre and Miquelon)")}>+508 (Saint Pierre and Miquelon)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1784 (saint vincent and the grenadines)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1784 (Saint Vincent and the Grenadines)")}>+1784 (Saint Vincent and the Grenadines)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+684 (samoa)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+684 (Samoa)")}>+684 (Samoa)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+378 (san marino)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+378 (San Marino)")}>+378 (San Marino)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+239 (sao tome and principe)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+239 (Sao Tome and Principe)")}>+239 (Sao Tome and Principe)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+966 (saudi arabia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+966 (Saudi Arabia)")}>+966 (Saudi Arabia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+221 (senegal)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+221 (Senegal)")}>+221 (Senegal)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+381 (serbia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+381 (Serbia)")}>+381 (Serbia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+248 (seychelles)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+248 (Seychelles)")}>+248 (Seychelles)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+232 (sierra leone)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+232 (Sierra Leone)")}>+232 (Sierra Leone)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+65 (singapore)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+65 (Singapore)")}>+65 (Singapore)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+421 (slovakia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+421 (Slovakia)")}>+421 (Slovakia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+386 (slovenia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+386 (Slovenia)")}>+386 (Slovenia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+677 (solomon islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+677 (Solomon Islands)")}>+677 (Solomon Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+252 (somalia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+252 (Somalia)")}>+252 (Somalia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+27 (south africa)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+27 (South Africa)")}>+27 (South Africa)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+82 (south korea)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+82 (South Korea)")}>+82 (South Korea)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+211 (south sudan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+211 (South Sudan)")}>+211 (South Sudan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+34 (spain)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+34 (Spain)")}>+34 (Spain)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+94 (sri lanka)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+94 (Sri Lanka)")}>+94 (Sri Lanka)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+249 (sudan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+249 (Sudan)")}>+249 (Sudan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+597 (suriname)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+597 (Suriname)")}>+597 (Suriname)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+268 (swaziland)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+268 (Swaziland)")}>+268 (Swaziland)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+46 (sweden)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+46 (Sweden)")}>+46 (Sweden)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+41 (switzerland)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+41 (Switzerland)")}>+41 (Switzerland)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+963 (syrian arab republic)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+963 (Syrian Arab Republic)")}>+963 (Syrian Arab Republic)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+886 (taiwan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+886 (Taiwan)")}>+886 (Taiwan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+992 (tajikistan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+992 (Tajikistan)")}>+992 (Tajikistan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+255 (tanzania, united republic of)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+255 (Tanzania, United Republic of)")}>+255 (Tanzania, United Republic of)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+66 (thailand)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+66 (Thailand)")}>+66 (Thailand)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+670 (timor-leste)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+670 (Timor-Leste)")}>+670 (Timor-Leste)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+228 (togo)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+228 (Togo)")}>+228 (Togo)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+690 (tokelau)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+690 (Tokelau)")}>+690 (Tokelau)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+676 (tonga)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+676 (Tonga)")}>+676 (Tonga)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 868 (trinidad and tobago)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 868 (Trinidad and Tobago)")}>+1 868 (Trinidad and Tobago)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+216 (tunisia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+216 (Tunisia)")}>+216 (Tunisia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+90 (turkey)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+90 (Turkey)")}>+90 (Turkey)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+993 (turkmenistan)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+993 (Turkmenistan)")}>+993 (Turkmenistan)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 649 (turks and caicos islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 649 (Turks and Caicos Islands)")}>+1 649 (Turks and Caicos Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+688 (tuvalu)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+688 (Tuvalu)")}>+688 (Tuvalu)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+256 (uganda)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+256 (Uganda)")}>+256 (Uganda)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+380 (ukraine)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+380 (Ukraine)")}>+380 (Ukraine)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+971 (united arab emirates)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+971 (United Arab Emirates)")}>+971 (United Arab Emirates)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+44 (united kingdom)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+44 (United Kingdom)")}>+44 (United Kingdom)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 868 (united states)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 868 (United States)")}>+1 868 (United States)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 242 (bahamas)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 242 (Bahamas)")}>+1 242 (Bahamas)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 664 (anguilla)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 664 (Anguilla)")}>+1 664 (Anguilla)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 473 (grenada)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 473 (Grenada)")}>+1 473 (Grenada)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 284 (british virgin islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 284 (British Virgin Islands)")}>+1 284 (British Virgin Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 345 (cayman islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 345 (Cayman Islands)")}>+1 345 (Cayman Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 473 (grenada)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 473 (Grenada)")}>+1 473 (Grenada)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 684 (american samoa)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 684 (American Samoa)")}>+1 684 (American Samoa)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 649 (turks and caicos islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 649 (Turks and Caicos Islands)")}>+1 649 (Turks and Caicos Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 721 (sint maarten)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 721 (Sint Maarten)")}>+1 721 (Sint Maarten)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 284 (british virgin islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 284 (British Virgin Islands)")}>+1 284 (British Virgin Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 758 (saint lucia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 758 (Saint Lucia)")}>+1 758 (Saint Lucia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 242 (bahamas)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 242 (Bahamas)")}>+1 242 (Bahamas)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 345 (cayman islands)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 345 (Cayman Islands)")}>+1 345 (Cayman Islands)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 758 (saint lucia)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 758 (Saint Lucia)")}>+1 758 (Saint Lucia)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 721 (sint maarten)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 721 (Sint Maarten)")}>+1 721 (Sint Maarten)</p>
                <p className={`px-4 py-[6px] hover:bg-blue-100 shadow-[0_0_.5px_gray_inset] cursor-default ${!("+1 684 (american samoa)".includes(search?.toLowerCase())) && "hidden"}`} onClick={e => setCountryCode("+1 684 (American Samoa)")}>+1 684 (American Samoa)</p>


            </div>
        </div>
    )
}
