import "./globals.css";
import AuthProvider from "./_components/AuthenticationProvider";
import { cookies } from 'next/headers';

export const metadata = {
  title: "Ecommerse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const { value : initial_theme } = cookieStore.get('theme');
  
  return (
    <html lang="en" className="">
    <AuthProvider initial_theme={initial_theme}>
      {children}
    </AuthProvider >
    </html>
  );
}
