import "./globals.css";
import Wrapper from "./_components/Wrapper";
import { getJWTUser } from "@/utils/getJWTUser";

export const metadata = {
  title: "Ecommerse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const user = getJWTUser();
  return (
    <html lang="en" className="">
      <Wrapper user={user}>
        {children}
      </Wrapper>
    </html>
  );
}
