import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/Navbar";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-950 text-white">
      <body className="flex flex-col items-center justify-between w-full" style={{minHeight:"calc(100vh)"}}>
        <NavBar />
        <div className="w-full flex-1">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
